# Analyse Univarié, Bivariée et Graphiques


Avant de mener des analyses à l'aide de modèle de régression et
autres statistiques complexes, il est préférable de tirer le
maximum de l'exploration des données et de statistiques
simples. Cela a deux avantages:

- permettre de mieux connaître les données et donc de repérer
leurs particularités et leurs éventuelles incohérences, ce qui
pourra servir pour des analyses statistiques plus
approfondies;
- permettre de sélectionner des indices et des graphiques
simples qui rendent le mieux compte des données afin de les
restituer à un large public: les connaissances en statistique de
la plupart des mortels ne dépassent guère le pourcentage, et
de toute façon, même un public de spécialistes ne retiendra en
définitive que les indices et les graphiques les plus simples.

Stata offre de nombreuses commandes pour l'analyse
exploratoire des données, autant sous forme de tableaux que de
graphiques. Comme dans les chapitres précédents, nous
utiliserons le fichier « census.dta » pour illustrer ces
commandes.

## Analyses univariées et bivariées

La commande *codebook* permet de faire le tri à plat de la base des données en montrant les sttatisques simples et univariées.  Et montre toute les informations nécéssaires à la compréhention de la structure d'une variable.

La commande *summarize* listvar permet aussi de résumer
la distribution, en particulier pour les variables numériques
continues. Cela n'aurait pas grand sens, par exemple, de calculer
la moyenne d'une variable discrète.

L'option detail pennet une description plus precIse des
variables continues, incluant les pourcentiles, les quatre plus
grandes (Largest) et plus basses (Smallest) valeurs, ainsi
qu'un indice de dissymétrie (la valeur de Skewness est °pour
la distribution nonnale) et de concentration (la valeur de
Kurtosis est de 3 pour la distribution normale.

À l'inverse de la commande swmnarize, la commande tabulate est utile pour les variables discrètes.

On remarque avec l'option nolabel (pour afficher les codes plutôt que les libellés), que les régions sont classées selon leur numéro de code:




###  Tableaux croisés à deux variables

La commande tabulate devient vraiment intéressante pour croiser les distributions de deux variables discrètes. La syntaxe de base de cette commande est:  

`tabulate varligne varcol[, cell column row missing nofreq wrap nolabel  chi2 exact gamma lrchi2 iaub v]`

Les modalités de la première variable citée figurent en ligne, tandis que les modalités de la deuxième apparaissent en colonne. Des options permettent d'obtenir les pourcentages en ligne (row) , en colonne (column) ou par cellule (cell) du tableau:

Pour afficher les pourcentages sans les fréquences, on utilisera l'option *nofreq*.


*Tableaux croisés à trois variables*

Le préfixe by listvar est utilisé pour produire des tableaux
croisés à deux variables pour chaque combinaison des modalités
des variables énumérées dans listvar. Si une seule variable
est énumérée dans listvar, on obtient un tableau croisé à trois
variables, si deux variables sont énumérées, un tableau croisé à
quatre variables, etc. Le préfixe by nécessite un tri préalable
selon les variables énumérées: 

`sort actif`

`by urbain: tabulate actif region, all exact`

L'option summarize (var) est une alternative au préfixe by
pour obtenir le croisement de trois variables, ou plutôt le résumé
d'une troisième variable dans les cases d'un tableau croisant
deux variables. Par exemple, si l'on veut obtenir la population
moyenne par États dans chacune des régions selon leur caractère
urbain ou rural, on exécutera:

`tabulate urbain region, summarize(pop) nostandard`

On a ajouté l'option nostandard pour éviter le calcul des
écarts types (standard deviation). Pour afficher seulement les populations moyennes (sans les effectifs), on peut ajouter
l'option nofreq.

L'option swnmarize () n'est pas seulement utile pour les
variables continues, telles que les effectifs de population, les
revenus, etc. Elle est aussi utile pour résumer les variables
ordinales (voir exercice précédent) et aussi les variables
dichotomiques. En effet, il faut savoir que la moyenne d'une
variable dichotomique est une proportion. Par exemple, pour
connaître la proportion d'États à dominante active selon la région et le caractère dominant urbain ou rural, on exécutera:

`tabulate urbain region, summarize(actif) nostandard nofreq`



## Indroduction aux graphiques sous Stata

Stata permet d'obtenir rapidement une description des données,
à l'aide de statistiques de distribution uni-, bi-, ou multivariée. En outre, Stata a aussi des capacitées visuelles importantes à exploiter lors de la description et de l'exploration des données.  


La commande graphique de Stata produit huit types de graphiques (histogramme, bâton, trait, boîte, point, matrice, étoile, camembert) qui peuvent être combinés, par exemple comme ceci: 





En outre, on peut associer diverses courbes de lissage aux graphiques uni- et bivariés (densité de Kemel, méthode des intervalles, etc.). La combinaison des diverses techniques de
représentations sur un même graphique permet de synthétiser les informations :

`graph pctact pcturb [fw=pop], twoway oneway box symbol((state]) connect(m) band(5) tlab rlab`


### Commande ppour les graphiques
Pour ce qui concerne les options communes à tous les types de
graphiques, la syntaxe de base de la commande *graph* est:

- `graph [listvar]`
- `[,options spécifiques au type de graphique `
- `by(nonvar) total`
- `x/y/r/tlabel x/y/r/ttick x/y/r/tline`
- `x/y/rcale y/x/rlog`
- `symbol(s...s) connect(c...c)`
- `saving(nomfichier,[replace])  ]`


Les options communes concernent essentiellement la mise en
forme du graphique: libellés (label), graduations (tick) , lignes
(line) , échelle des axes (scale, log), symboles (symbol), liaison
des points (connect). Nous n'avons fait figurer ici que les
options les plus courantes. Pour une description des options
avancées pour les titres, la taille des caractères, l'épaisseur des
traits et les couleurs, voir les exemples qui sont donnés dans le
manuel de référence aux entrées graph titles, graph textsize,
graph pens, graph shading.

Les options spécifiques au type de graphique sont décrites dans
les sections suivantes, ainsi que les commandes spécifiques qui
s'apparentent à la commande *graph*.



#### Les variables discrètes
(1) Graphiques de répartition discrète: barres, camemberts et étoiles

La commande graph produit par défaut un histogramme
lorsqu'une seule variable figure dans la liste des variables.
Certaines options sont spécifiques aux histogrammes:




Le graphique a sans doute plus d'intérêt si l'on croise deux
variables discrètes avec l'option by () après avoir trié le fichier
selon la variable spécifiée (voir le chapitre Création et
correction de variables pour la création de la variable urbain) :




#### Les variables continues

histogrammes

elles servent à representer visuellement la distribution d'une variable quantitative que l'on découpe en classes.


boites à moustaches

Pour visualiser les paramètres de position d'une variable quantitative. La commande type est 
`graph box x` . Si on souhaite comparer la distritution de x dans les différentes sous-échantillon selon une variable qualitative, on ajoute l'option by ou over (avec la variable de groupe entre parenthèses) à la commande de base . On obtient la structure suivante : 

`graph box x, by(y)`
`graph box x, over(y)`


nuages des points et droite d'ajustement

ce type de graphique est utilisé pour le croisement de deux variables quantitatives. Pour la representation visuelle de l'association entre deux variables quantitatives.
La terminologie pour ce type de graphique est **scatter**. 

La synthaxe pour cette commande est 

`graph scatter y x`

avec y la variable à placer en ordonnée et x la variable en abscisse


Pour l'ajustement, on utilise la commande `lfit x y` avec *lfit* l'argument pour spécifier la droite d'ajustement sous forme linéaire. On peut aussi utiliser la commande *lowess* pour un ajustement sous forme de courbe.

Note. 

Il est tout même possible de supperposer deux graphiques , à conditions que ces graphiques soit travé avec une même variabe en abscisse. La commande twoway est utilisée pour cette fin. La synthawe est la suivante :

`graph twoway (scatter x y) (lfit x y) `

dans le cas où on souhaiterait superposer le nuage des points des variables x, y et leur droite d'ajustement sur un seul graphique.



Les graphiques de distribution

ces graphiques sont utilisées lors que l'on souhaite voir ka distribution d'une variable , on que l'on souhaite ajuster la distribution empirique , à une distribution théorique : normal, poisson, exponentielle, exponentielle négative, weibull , ...

(1) Kernel density et qnorm

`kdensity x , qnorm` pour tester la distribution d'une variable quantitative à la distribution typique d'une variable suivant la loi normal.

(2) Le Q-Q plot



Les graphiques multivariées

En fait, les graphiques dits multivariés sont des superpositions,
ou des alignements de graphiques univariés ou bivariés. Nous
avons déjà vu comment faire de tels graphiques avec l'option
by (var) commune à de nombreuses commandes. Cette section
est consacrée aux graphiques multivariés qui ne font pas appel à
l'option by.

L'option matrix établit une sene de graphiques bivariés
croisant chaque paire de variables énumérées:

#### La graph editor

C'est une interface graphique qui permet de spécifier les éléments graphiques tels que les titres, les titres des axes, la légende, ...

